[subsection Atom]

This project uses the Atom project and packages as its foundation for
storing individual strings.

[para] Please go to either the main repository at
[uri http://core.tcl.tk/akupries/atom]

or the backup at
[uri http://chiselapp.com/andreas_kupries/repositories/atom]

and follow the instructions given at these sites to create a working
installation. They are not repeated here. If there are problems with
these instructions please file a bug against the Atom project, and not
[package [vset PTITLE]].

[para]
