
[subsection DbUtil]

Dbutil is required by the [package atom::sqlite] package.

[para] The package can be found
at  [uri https://core.tcl.tk/akupries/dbutil]
and [uri https://chiselapp.com/user/andreas_kupries/repository/dbutil]

[para] You will have to build and install it on your own, because as
far as I know it is not included in any type of distribution yet. The
necessary instructions for that are found at the sites referenced
above.

[para] If there are problems with building, installing, or using
DbUtil please file a bug against DbUtil itself, and not
[package [vset PROJECT]].
